server:
  port: 10000
  servlet:
    session:
      tracking-modes: COOKIE
      cookie:
        http-only: true
        secure: false
        same-site: lax
      timeout: 10m

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EC2_HOST}:5432/app?serverTimezone=Asia/Seoul
    username: cw
    password: 1234
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: ${EC2_HOST}
      port: 6379
  cache:
    type: redis
  profiles:
    active: local
    include: oauth
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.crewstation.domain;com.example.crewstation.dto;
  type-handlers-package: com.example.crewstation.config.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: ${JWT_SECRET}

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ${AWS_S3_BUCKET}
  region: ${AWS_REGION}

sms:
  api:
    access: ${SMS_KEY}
    secret: ${SMS_SECRET}